name: Publish Docker Image
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set environment
        id: environment
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build and push image to registry
        uses: docker/build-push-action@v2
        env:
          RELEASE_VERSION: ${{ steps.environment.outputs.tag }}
        with:
          push: true
          no-cache: true
          context: .
          file: ./docker/build.dockerfile
          tags: |
            sverigestelevision/staticsrv:latest
            sverigestelevision/staticsrv:${{ env.RELEASE_VERSION }}
